In [1]:
#import library dasar
import pandas as pd
import os
import math
import numpy as np
import random
import matplotlib.pyplot as plt
from scipy.spatial import distance
from scipy import stats
from statistics import mean

In [2]:
#kasi tau lokasi disk
cwd = os.getcwd()
print(cwd)

/Users/macbookpro/Downloads/Damin tubes


In [3]:
#baca file
file = pd.read_csv("thyroid1.csv")
file

age gender  tsh   t3   t4 hypothyroid hyperthyroid
0      29      F  0.3    ?    ?           t            f
1      29      F  1.6  1.9  128           f            f
2      41      F    ?    ?    ?           f            t
3      36      F    ?    ?    ?           f            f
4      32      F    ?    ?    ?           f            f
...   ...    ...  ...  ...  ...         ...          ...
9167   56      M    ?    ?   64           f            t
9168   22      M    ?    ?   91           f            f
9169   69      M    ?    ?  113           f            f
9170   47      F    ?    ?   75           f            f
9171   31      M    ?    ?   66           t            f

[9172 rows x 7 columns]

In [4]:
results = []
for i in range (len(file['age'])):
    if file['hypothyroid'][i] == 't' and file['hyperthyroid'][i] == 'f':
        results.append("hypothyroid")
    elif (file['hyperthyroid'][i] == 't' and file['hypothyroid'][i] == 'f') or (file['hypothyroid'][i] == 't' and file['hyperthyroid'][i] == 't'):
        results.append("hyperthyroid")
    else:
        results.append("normal")

In [5]:
all = {'age': file['age'], 'gender': file['gender'], 'tsh': file['tsh'], 't3': file['t3'], 't4': file['t4'], 'results': results}
df = pd.DataFrame(all, columns = ['age','gender','tsh','t3','t4','results'])
df

age gender  tsh   t3   t4       results
0      29      F  0.3    ?    ?   hypothyroid
1      29      F  1.6  1.9  128        normal
2      41      F    ?    ?    ?  hyperthyroid
3      36      F    ?    ?    ?        normal
4      32      F    ?    ?    ?        normal
...   ...    ...  ...  ...  ...           ...
9167   56      M    ?    ?   64  hyperthyroid
9168   22      M    ?    ?   91        normal
9169   69      M    ?    ?  113        normal
9170   47      F    ?    ?   75        normal
9171   31      M    ?    ?   66   hypothyroid

[9172 rows x 6 columns]

In [6]:
# Get names of indexes for which column Age has value 30
indexNames = df[df['tsh'] == '?' ].index
# Delete these row indexes from dataFrame
df.drop(indexNames , inplace=True)

indexNames = df[df['t3'] == '?' ].index
df.drop(indexNames , inplace=True)

indexNames = df[df['t4'] == '?' ].index
df.drop(indexNames , inplace=True)

df

age gender   tsh   t3   t4      results
1      29      F   1.6  1.9  128       normal
7      28      F   0.7  2.6  116       normal
8      28      F   1.2  1.8   76       normal
9      28      F   1.9  1.7   83       normal
10     54      F   1.9  2.3  133       normal
...   ...    ...   ...  ...  ...          ...
9129   65      M  0.73  1.8   85       normal
9130   65      F   4.1  2.1  135  hypothyroid
9134   74      F    53    1   49       normal
9137   42      F   2.3  1.3   59  hypothyroid
9141   42      F   2.4  1.8  102       normal

[6325 rows x 6 columns]

In [7]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()

encoded1 =le.fit_transform(df['age'])
encoded2 =le.fit_transform(df['gender'])
encoded3 =le.fit_transform(df['tsh'])
encoded4 =le.fit_transform(df['t3'])
encoded5 =le.fit_transform(df['t4'])
label = le.fit_transform(df['results'])
features = list(zip(encoded1,encoded2,encoded3,encoded4,encoded5))

In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(features, label, test_size=0.20)

In [9]:
#import knn
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=5)

# train model
knn.fit(X_train, y_train)

# ubah prediksi
y_pred = knn.predict(X_test)

In [10]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print (classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.20      0.03      0.06        92
           1       0.09      0.01      0.03        69
           2       0.87      0.98      0.93      1104

    accuracy                           0.86      1265
   macro avg       0.39      0.34      0.34      1265
weighted avg       0.78      0.86      0.81      1265



In [11]:
#kalsifikasi menggunakan Naive Bayes
from sklearn.naive_bayes import GaussianNB
clf = GaussianNB()
clf.fit(X_train, y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [12]:
result = clf.predict(X_test)

In [13]:
result

array([2, 2, 2, ..., 2, 2, 2])

In [14]:
clf.score(X_test, y_test)*100

86.32411067193677

In [15]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print (classification_report(y_test, result))

              precision    recall  f1-score   support

           0       0.21      0.05      0.09        92
           1       0.00      0.00      0.00        69
           2       0.88      0.98      0.93      1104

    accuracy                           0.86      1265
   macro avg       0.36      0.35      0.34      1265
weighted avg       0.78      0.86      0.82      1265



/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [16]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [17]:
# Klasifikasi menggunakan Decision Tree Classification
from sklearn.tree import DecisionTreeClassifier, plot_tree
classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=0, splitter='best')

In [18]:
result2 = clf.predict(X_test)

In [19]:
result2

array([2, 2, 2, ..., 2, 2, 2])

In [20]:
clf.score(X_test, y_test)*100

87.27272727272727

In [21]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print (classification_report(y_test, result2))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00        92
           1       0.00      0.00      0.00        69
           2       0.87      1.00      0.93      1104

    accuracy                           0.87      1265
   macro avg       0.29      0.33      0.31      1265
weighted avg       0.76      0.87      0.81      1265



/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [22]:
from sklearn import svm
X = X_train
y = y_train
clf = svm.SVC()
clf.fit(X, y)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='rbf', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

In [23]:
result3 = clf.predict(X_test)

In [24]:
result3

array([2, 2, 2, ..., 2, 2, 2])

In [25]:
clf.score(X_test, y_test)*100

87.27272727272727

In [26]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print (classification_report(y_test, result3))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00        92
           1       0.00      0.00      0.00        69
           2       0.87      1.00      0.93      1104

    accuracy                           0.87      1265
   macro avg       0.29      0.33      0.31      1265
weighted avg       0.76      0.87      0.81      1265



/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
